### ISSUE TITLE
Setup QVGA for higher frame rates

### ISSUE THREAD

**Issue by neumann89** [ATLFlight/dfs-ros-example#2]
Hi! When I change the downsample_factor to value 2 in `config/dfs_test.yaml`. I assumed that it reduces the image resolution und depth processing is faster.

But it still runs with 2-3 Hz only. Do I have to change something more to run it faster?

**Comment by sgibsongithub** [comment]
Hello, @neumann89 !

I apologize for the confusion; downsample_factor is no longer used. I just pushed a new version where that parameter is deleted to avoid future confusion.

In order to use QVGA resolution, you need a calibration file corresponding to QVGA. (The resolution is set by reading the 'size' attribute in the calibration file--see lines 67-82 and 296-299 of src/nodes/SnapdragonRosNodeDfs.cpp.) So for QVGA, set the size to 320x240, and make sure to divide the principal points and focal lengths by 2 as well.

I've also uploaded a new script, setperfmode.sh, which can be run to set the GPUs and CPUs to performance mode. This should help increase the FPS.

Finally, you could decrease the number of disparity levels. For 28 disparity levels, assuming narrow FOV cameras with focal length ~217, this would correspond to a closest detectable distance of 0.6 m.

Here are the performance numbers I'm seeing for DFS:
VGA, 32 disparity levels: 2.5 Hz
QVGA, 32 disparity levels: 14 Hz
QVGA, 32 disparity levels, performance mode: 19 Hz
QVGA, 28 disparity levels, performance mode: 22 Hz

Hope this helps.

**Comment by neumann89** [comment]
Hi @sgibsongithub !

I changed the calibration file to QVGA + added the setpermode script and now I'm able to get higher frame rates as you mentioned.

QVGA, 32 disparity levels: 13.6 Hz
QVGA, 32 disparity levels, performance mode: 19.8 Hz

Thanks for your answer!
